@extends('layouts.app', ['title' => 'Dues Payment Transactions'])

@section('content')
@php($debugMode = \App\Models\Setting::value('system_mode', 'production') === 'debug')
@if($pendingDeletionRequests->isNotEmpty())
<div class="card card-warning"><div class="card-header"><h3 class="card-title"><i class="fas fa-user-check"></i> Deletion Requests Awaiting Second-Admin Review</h3></div><div class="card-body">
@foreach($pendingDeletionRequests as $deletionRequest) @php($receipt = $deletionRequest->receipt) <div class="approval-request"><div><strong>{{ $receipt?->staff?->full_name ?: $deletionRequest->payment?->staff?->full_name }}</strong> — GHS {{ number_format((float) ($receipt?->amount ?: $deletionRequest->payment?->amount), 2) }}<br><small>Requested by {{ $deletionRequest->requester?->name }}: {{ $deletionRequest->reason }}</small></div>@if($deletionRequest->requested_by === auth()->id())<span class="badge badge-secondary">Waiting for another admin</span>@else<div class="approval-actions"><form method="post" action="{{ route('admin.dues.deletion-requests.approve', $deletionRequest) }}">@csrf<div class="input-group input-group-sm"><input name="password" type="password" class="form-control" placeholder="Your password" required><div class="input-group-append"><button class="btn btn-danger">Approve Delete</button></div></div></form><form method="post" action="{{ route('admin.dues.deletion-requests.reject', $deletionRequest) }}">@csrf<div class="input-group input-group-sm"><input name="password" type="password" class="form-control" placeholder="Your password" required><input name="review_notes" class="form-control" placeholder="Reason (optional)"><div class="input-group-append"><button class="btn btn-outline-secondary">Reject</button></div></div></form></div>@endif</div> @endforeach
</div></div>
@endif
<div class="card"><div class="card-body table-responsive"><table class="table table-bordered table-sm"><thead><tr><th>Recorded</th><th>Payment Date</th><th>Staff</th><th>Original Amount</th><th>Allocated Across</th><th>Method</th><th>Reference</th><th>Recorded By</th><th></th></tr></thead><tbody>
@foreach($receipts as $receipt)
@php($representative = $receipt->allocations->first())
<tr><td>{{ $receipt->created_at?->format('Y-m-d H:i:s') }}</td><td>{{ $receipt->payment_date?->format('Y-m-d') }}</td><td>{{ $receipt->staff?->full_name }}</td><td><strong>GHS {{ number_format((float) $receipt->amount, 2) }}</strong></td><td><button class="btn btn-sm btn-outline-info" type="button" data-toggle="collapse" data-target="#allocations{{ $receipt->id }}">{{ $receipt->allocations->count() }} month(s)</button></td><td>{{ $receipt->payment_method }}</td><td>{{ $receipt->reference_number }}</td><td>{{ $receipt->recorder?->name }}</td><td>@if($receipt->deletionRequests->isNotEmpty() && ! $debugMode)<span class="badge badge-warning">Approval pending</span>@elseif($representative)<button class="btn btn-sm btn-outline-danger" type="button" data-toggle="collapse" data-target="#deleteReceipt{{ $receipt->id }}"><i class="fas fa-trash"></i> {{ $debugMode ? 'Delete Now' : 'Request' }}</button>@endif</td></tr>
<tr class="collapse allocation-detail-row" id="allocations{{ $receipt->id }}"><td colspan="9"><div class="allocation-chips">@foreach($receipt->allocations as $allocation)<span>{{ \App\Services\DuesCalculationService::MONTHS[$allocation->payment_month] }} {{ $allocation->payment_year }}: GHS {{ number_format((float) $allocation->amount,2) }}</span>@endforeach</div></td></tr>
@if($representative && ($receipt->deletionRequests->isEmpty() || $debugMode))<tr class="collapse" id="deleteReceipt{{ $receipt->id }}"><td colspan="9"><form method="post" action="{{ route('admin.dues.deletion-request', $representative) }}" class="deletion-request-form">@csrf<div><strong>{{ $debugMode ? 'Delete complete receipt immediately' : 'Request complete receipt deletion' }}</strong><small class="d-block text-muted">All {{ $receipt->allocations->count() }} monthly allocations will be removed together.</small></div><input name="reason" class="form-control" placeholder="Reason for deletion" required><input name="password" type="password" class="form-control" placeholder="Your password" required><button class="btn btn-danger">{{ $debugMode ? 'Delete Receipt' : 'Submit Request' }}</button></form></td></tr>@endif
@endforeach
</tbody></table>{{ $receipts->links() }}</div></div>
@endsection
